### ISSUE TITLE
一个想法

### ISSUE THREAD

**Issue by ghost** [CareF/deepin-dock-plugin-arch-update#1]
图标颜色太浅，可以改成类似自带插件的纯白色

**Comment by CareF** [comment]
我美术功底太差, 直接复制的 https://github.com/RaphaelRochet/arch-update 的图标. 看了下 Arch logo 和 右下角标示还有灰度就没下手改.. 其实也不知道怎么改. 朋友你会处理 svg 格式图标吗?

**Comment by ghost** [comment]
https://pan.baidu.com/s/1kCOgbn4cRWnMJlpDOZs4Dg
只用魔法棒和油漆桶简单处理了一下，替换了一下感觉观感还行

**Comment by CareF** [comment]
你的这个文件不知道为什么我本地打不开.. 不过我用 Inkscape 把它换成白色试了下, 感觉... 
嗯你是不是和我一样用的 "高效模式"? 主要是 deepin 给的 API 并不运行我把插件图标收到时尚模式中间那栏和自带插件在一起, 用白色就有点违和了. 
我想了想把高效模式下改成白色, 时尚模式保持原来不变. white 分支 (https://github.com/CareF/deepin-dock-plugin-arch-update/tree/white) 你看下?

**Comment by ghost** [comment]
我也是高效模式，这样设计应该不错，但是现在我在white 分支“已是最新”状态下图标看不见，其他没问题

**Comment by CareF** [comment]
是个 bug (资源文件里有个 typo) .. 刚发现已经修好了.

**Comment by CareF** [comment]
那就先静置两天然后 merge 到 master 里加 tag 
https://github.com/CareF/deepin-dock-plugin-arch-update/commit/acb91c89e3fb165dd1c2b53154ad7b1b9a8d6360
https://github.com/CareF/deepin-dock-plugin-arch-update/commit/c10fffe830e9a7ff86b80a9f420b14903d1a6911

**Comment by ghost** [comment]
可以了，解决了我的问题，谢谢
