### ISSUE TITLE
Excessive CPU Usage

### ISSUE THREAD

**Issue by sayoojsamuel** [CareF/deepin-dock-plugin-arch-update#2]
The CPU usage jumps to 100% after update with `arch-update` dde-dock plugin.  The CPU usage drops with the plugin is disabled from dde-dock settings. 

![Screen Capture_select-area_20200530023853](https://user-images.githubusercontent.com/31436104/83306103-9a062000-a21f-11ea-9357-89ac56b30ebf.png)

Not sure about the steps to reproduce.  
I'm running Arch with Deepin v20 beta. 

**ArchUpdate Version**: 1.2

**Comment by CareF** [comment]
I've never seen this, and nothing in the plugin is CPU intense, so there is likely a bug, either in the interface between the plugin and dde-dock or on the system. 

If you can try start dde-dock from terminal by: 
```
pkill dde-dock
dde-dock
```
which will enable log info to be printed on screen, and check if there is anything that looks weird and relevant? 

And if it's a one time thing... I would say DDE is still a young software and many small buggy things can happen.

**Comment by sayoojsamuel** [comment]
I guess it's a one time bug, because I cannot reproduce this issue. 

Cool plugin by the way! Cheers!
